### ISSUE TITLE
Build inventory of all CfP servers

### ISSUE THREAD

**Issue by lottspot** [CodeForPhilly/ops#1]
Before we can know what to do, we need to know what we have. We will need to gather a detailed inventory of what machines are currently active, what application stacks are installed on them, what provider they are hosted with, what web applications are hosted on them, and really every other detail we can get our hands on.

This task can be moved into the "ready" state once:
- We have decided how to record inventory
- Our group or some subset thereof has access to the machines which we need to inventory

**Comment by lottspot** [comment]
I think the wise choice is to use an External Node Classifier to model our inventory. In addition to providing us with a powerful attribute-driven overview of the ecosystem we'll be managing, taking this approach will allow us to plug our inventory data into a configuration management tool of our choice once the time comes.

**Comment by lottspot** [comment]
The two ENCs I think we should be looking at are [Hiera](https://docs.puppet.com/hiera/3.1/) and [Reclass](http://reclass.pantsfullofunix.net/). Spoiler: I already have an opinion on which one I would prefer, but I want to hear what other people's thoughts are before committing to that opinion.

**Comment by themightychris** [comment]
@ub1quit33 without doing more than skimming through their docs and some discussions, reclass smells better to me

**Comment by lottspot** [comment]
This issue is pretty much obsolete
