### ISSUE TITLE
Bucket Storage Request

### ISSUE THREAD

**Issue by zzzuuk** [CodeForPhilly/ops#40]
## Request

The PLSE Project would like to request access for the purpose of storing data that we are using for our expungement and pardon services. We are in a crunch to get access since the information is coming from a publicly available database and the information started being hidden from public view on June 28. In two days, they already hid 170,000 records.

## Deployment specifications

We are look to store approx. 200GB of PDF files.

**Comment by themightychris** [comment]
I've provisioned buckets on both Linode and GCP. I had trouble using the Linode bucket so I set up the GCP bucket too. Use the GCP bucket for now, we'll mirror them with rclone if/when we get Linode or another bucket working

Credentials for both are available under the `PLSE Shared` collection in bitwarden
